// bench/bench.ts - NFR-1 measured through the real middleware, in-process.
// Advertised numbers come from here or do not appear (Constitution V.16).
//   run + update README table:  node --experimental-strip-types bench/bench.ts
//   CI gate (no README write):  node --experimental-strip-types bench/bench.ts --check
import { readFileSync, writeFileSync } from "node:fs";
import { hrtime } from "node:process";
import { fileURLToPath } from "node:url";
import { buildOffer, verifyProof } from "@tollbooth/adapter-x402";
import { generateSecretKey, mintVoucher, publicKeyOf } from "@tollbooth/core";
import { tollbooth } from "@tollbooth/hono";
import { Hono } from "hono";

const HUMAN = {
  "user-agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
  accept: "text/html,*/*;q=0.8",
};
const CURL = { "user-agent": "curl/8.7.1", accept: "*/*" };

const TOLL = `
mode = "toll"
[toll.x402]
pay_to = "0x1111111111111111111111111111111111111111"
`;

const VOUCHER_CFG = `
mode = "toll"
[toll.x402]
enabled = false
[toll.stripe]
enabled = true
payment_link = "https://buy.stripe.com/test_x"
webhook_secret = "whsec_x"
bearer = true
`;

async function measure(run: () => unknown, warmup = 200, samples = 2000) {
  for (let i = 0; i < warmup; i++) await run();
  const times: number[] = [];
  for (let i = 0; i < samples; i++) {
    const start = hrtime.bigint();
    await run();
    times.push(Number(hrtime.bigint() - start) / 1e6);
  }
  times.sort((a, b) => a - b);
  const q = (p: number) => times[Math.floor(p * (times.length - 1))] as number;
  return { p50: q(0.5), p99: q(0.99) };
}

const baseline = new Hono();
baseline.get("*", (c) => c.text("ok"));

const tolled = new Hono();
tolled.use(
  tollbooth({
    config: TOLL,
    x402: { buildOffer, verifyProof },
    fetchDirectory: async () => ({ keys: [] }),
  }),
);
tolled.get("*", (c) => c.text("ok"));

const siteSecret = generateSecretKey();
const voucherApp = new Hono();
voucherApp.use(
  tollbooth({
    config: VOUCHER_CFG,
    siteKeys: { secret: siteSecret, pub: await publicKeyOf(siteSecret) },
    fetchDirectory: async () => ({ keys: [] }),
  }),
);
voucherApp.get("*", (c) => c.text("ok"));
const nowS = Math.floor(Date.now() / 1000);
let voucher = await mintVoucher(
  { agentKey: null, credits: 10_000, expiresS: nowS + 86_400, nowS },
  siteSecret,
);

const rows: Array<{ name: string; p50: number; p99: number }> = [];
const scenarios: Array<[string, () => unknown]> = [
  [
    "baseline app, no tollbooth",
    () => baseline.request("http://x.test/a", { headers: HUMAN }),
  ],
  [
    "human pass-through",
    () => tolled.request("http://x.test/a", { headers: HUMAN }),
  ],
  [
    "free path pass-through",
    () => tolled.request("http://x.test/robots.txt", { headers: CURL }),
  ],
  [
    "agent 402 offer",
    () => tolled.request("http://x.test/a", { headers: CURL }),
  ],
  [
    "voucher spend + re-sign (ed25519 x2)",
    async () => {
      const resp = await voucherApp.request("http://x.test/a", {
        headers: { ...CURL, "tollbooth-voucher": voucher },
      });
      voucher = resp.headers.get("tollbooth-voucher") ?? voucher;
    },
  ],
];
for (const [name, run] of scenarios)
  rows.push({ name, ...(await measure(run)) });

const fmt = (ms: number) => `${ms.toFixed(3)} ms`;
const base = rows[0] as { p50: number; p99: number };
const human = rows[1] as { p50: number; p99: number };
const addedP50 = Math.max(0, human.p50 - base.p50);
const addedP99 = Math.max(0, human.p99 - base.p99);
const pass = addedP50 <= 1 && addedP99 <= 5;

const table = [
  "| scenario | p50 | p99 |",
  "|---|---|---|",
  ...rows.map((r) => `| ${r.name} | ${fmt(r.p50)} | ${fmt(r.p99)} |`),
].join("\n");
const verdict = `NFR-1 (pass-path added latency <= 1 ms p50, <= 5 ms p99): **${pass ? "PASS" : "FAIL"}** (added p50 ${fmt(addedP50)}, added p99 ${fmt(addedP99)})`;

console.log(`${table}\n\n${verdict}`);

if (process.argv.includes("--check")) {
  process.exit(pass ? 0 : 1);
}

const readmePath = fileURLToPath(new URL("../README.md", import.meta.url));
const readme = readFileSync(readmePath, "utf8");
const section = `<!-- bench:start -->\n_Generated by \`bench/bench.ts\` on Node ${process.version}; in-process \`app.request\`, 2000 samples per row._\n\n${table}\n\n${verdict}\n<!-- bench:end -->`;
const updated = readme.includes("<!-- bench:start -->")
  ? readme.replace(/<!-- bench:start -->[\s\S]*<!-- bench:end -->/, section)
  : `${readme.trimEnd()}\n\n## Benchmarks\n\n${section}\n`;
writeFileSync(readmePath, updated);
console.log(`README.md ${readme === updated ? "unchanged" : "updated"}`);
